# Generated by Django 3.1.6 on 2021-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibilitie', models.TextField()),
                ('tech_skill', models.TextField()),
                ('soft_skill', models.TextField()),
            ],
        ),
    ]
