# Generated by Django 3.1.6 on 2021-02-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20210212_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='soft_skill',
            new_name='soft_skills',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='tech_skill',
            new_name='tech_skills',
        ),
    ]
