# Generated by Django 3.1.6 on 2021-02-15 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20210212_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='sample_CV',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
