# Generated by Django 3.1.6 on 2021-02-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_response_sample_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_CV', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='sample_CV',
        ),
    ]
