# Generated by Django 3.1.6 on 2021-02-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0006_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
